from utilidades import crear_grafo
grafo = crear_grafo()
print("CIUDADES")
grafo.mostrar_ciudades()
print()
print("RUTAS")
grafo.mostrar_rutas()
print()
print("LISTA DE ADYACENCIA")
grafo.mostrar_lista_adyacencia()
print()
print("GRADOS")
grafo.mostrar_grados()
print()
print("INFORMACIÓN")
grafo.informacion()
print()
print("BFS DESDE QUITO")
recorrido, niveles, padres = grafo.bfs("Quito")
print("Recorrido:", recorrido)
print("\nNiveles:")
for ciudad, nivel in niveles.items():
    print(f"{ciudad}: {nivel}")
print()
print("DFS DESDE QUITO")
recorrido = grafo.dfs("Quito")
print("Recorrido:", recorrido)
print()
print("DIJKSTRA DESDE QUITO")
grafo.mostrar_dijkstra("Quito")
print()
print("RUTA MÁS CORTA")
ruta, distancia = grafo.ruta_mas_corta("Quito","Cuenca")
print("Ruta:", " -> ".join(ruta))
print("Distancia:", distancia, "km")
print()
print("COMPARACIÓN BFS vs DIJKSTRA")
grafo.mostrar_comparacion("Quito","Cuenca")
print()
print("CIUDAD MÁS CERCANA")
ciudad, distancia = grafo.ciudad_mas_cercana("Quito")
print(ciudad)
print(distancia, "km")
print()
print("CIUDAD MÁS LEJANA")
ciudad, distancia = grafo.ciudad_mas_lejana("Quito")
print(ciudad)
print(distancia, "km")
print()
print("MATRIZ DE ADYACENCIA")
ciudades, matriz = grafo.matriz_adyacencia()
print("{:<12}".format(""), end="")
for ciudad in ciudades:
    print("{:<12}".format(ciudad), end="")
print()
for i, ciudad in enumerate(ciudades):
    print("{:<12}".format(ciudad), end="")
    for valor in matriz[i]:
        if valor == 0:
            print("{:<12}".format("-"), end="")
        else:
            print("{:<12}".format(valor), end="")
    print()
